### ISSUE TITLE
Reproduction failure

### ISSUE THREAD

**Issue by xujli** [CityChan/Federated-DPMS#2]
I can't reproduce the results. In all experiments, FedAvg has the best performance, FedMix is the worst. Take your bash command in $./scripts/train_fmnist.sh$ as example, FedAvg in my implements reaches 85.7% and FedMix reaches 74.5%. IDK what happening, may you give me some advises or implement details

**Comment by CityChan** [comment]
Could you tell me the bash commend you ran? And what's the accuracy of other methods?

**Comment by xujli** [comment]
> Could you tell me the bash commend you ran? And what's the accuracy of other methods?

I ran your methods of $FedAvg$, $FedProx$, $Moon$ and $FedMix$ in ./scripts/train_fmnist.sh with your presetting parameters. Final test accuracy of these methods when $beta=0.1$ are 85.77, 85.47, 78.86 and 74.55

**Comment by CityChan** [comment]
performance of all methods depends on  data heterogeneity, Moon and FedMix are not good when the local datasets are extremely non-iid

**Comment by CityChan** [comment]
> > Could you tell me the bash commend you ran? And what's the accuracy of other methods?
> 
> I ran your methods of FedAvg, FedProx, Moon and FedMix in ./scripts/train_fmnist.sh with your presetting parameters. Final test accuracy of these methods when beta=0.1 are 85.77, 85.47, 78.86 and 74.55

you also need to fine-tune for these methods

**Comment by xujli** [comment]
> > > Could you tell me the bash commend you ran? And what's the accuracy of other methods?
> > 
> > 
> > I ran your methods of FedAvg, FedProx, Moon and FedMix in ./scripts/train_fmnist.sh with your presetting parameters. Final test accuracy of these methods when beta=0.1 are 85.77, 85.47, 78.86 and 74.55
> 
> you also need to fine-tune for these methods

Yep I found this phenomenon in different $beta$ settings, with more skewed data distribution, more performance gap between FedAvg and FedMix or Moon, from 10% to 1.3%. I still wonder the how your produce the results in Figure 4(a), is \alpha in your fig is \beta in your caption? I have not seen any result case that FedMix has better test accuracy than FedAvg. Thanks for your quick reply.

**Comment by CityChan** [comment]
> > > > Could you tell me the bash commend you ran? And what's the accuracy of other methods?
> > > 
> > > 
> > > I ran your methods of FedAvg, FedProx, Moon and FedMix in ./scripts/train_fmnist.sh with your presetting parameters. Final test accuracy of these methods when beta=0.1 are 85.77, 85.47, 78.86 and 74.55
> > 
> > 
> > you also need to fine-tune for these methods
> 
> Yep I found this phenomenon in different beta settings, with more skewed data distribution, more performance gap between FedAvg and FedMix or Moon, from 10% to 1.3%. I still wonder the how your produce the results in Figure 4(a), is \alpha in your fig is \beta in your caption? I have not seen any result case that FedMix has better test accuracy than FedAvg. Thanks for your quick reply.

**Comment by CityChan** [comment]
> > > > Could you tell me the bash commend you ran? And what's the accuracy of other methods?
> > > 
> > > 
> > > I ran your methods of FedAvg, FedProx, Moon and FedMix in ./scripts/train_fmnist.sh with your presetting parameters. Final test accuracy of these methods when beta=0.1 are 85.77, 85.47, 78.86 and 74.55
> > 
> > 
> > you also need to fine-tune for these methods
> 
> Yep I found this phenomenon in different beta settings, with more skewed data distribution, more performance gap between FedAvg and FedMix or Moon, from 10% to 1.3%. I still wonder the how your produce the results in Figure 4(a), is \alpha in your fig is \beta in your caption? I have not seen any result case that FedMix has better test accuracy than FedAvg. Thanks for your quick reply.

\alpha is generation number of FedDPMS, \beta is Dirichlet Parameter

**Comment by xujli** [comment]
> > > > > Could you tell me the bash commend you ran? And what's the accuracy of other methods?
> > > > 
> > > > 
> > > > I ran your methods of FedAvg, FedProx, Moon and FedMix in ./scripts/train_fmnist.sh with your presetting parameters. Final test accuracy of these methods when beta=0.1 are 85.77, 85.47, 78.86 and 74.55
> > > 
> > > 
> > > you also need to fine-tune for these methods
> > 
> > 
> > Yep I found this phenomenon in different beta settings, with more skewed data distribution, more performance gap between FedAvg and FedMix or Moon, from 10% to 1.3%. I still wonder the how your produce the results in Figure 4(a), is \alpha in your fig is \beta in your caption? I have not seen any result case that FedMix has better test accuracy than FedAvg. Thanks for your quick reply.
> 
> \alpha is generation number of FedDPMS, \beta is Dirichlet Parameter

But in your figure, \alpha is concentration parameters, referring to your figures in README.

**Comment by CityChan** [comment]
> > > > > > Could you tell me the bash commend you ran? And what's the accuracy of other methods?
> > > > > 
> > > > > 
> > > > > I ran your methods of FedAvg, FedProx, Moon and FedMix in ./scripts/train_fmnist.sh with your presetting parameters. Final test accuracy of these methods when beta=0.1 are 85.77, 85.47, 78.86 and 74.55
> > > > 
> > > > 
> > > > you also need to fine-tune for these methods
> > > 
> > > 
> > > Yep I found this phenomenon in different beta settings, with more skewed data distribution, more performance gap between FedAvg and FedMix or Moon, from 10% to 1.3%. I still wonder the how your produce the results in Figure 4(a), is \alpha in your fig is \beta in your caption? I have not seen any result case that FedMix has better test accuracy than FedAvg. Thanks for your quick reply.
> > 
> > 
> > \alpha is generation number of FedDPMS, \beta is Dirichlet Parameter
> 
> But in your figure, \alpha is concentration parameters, referring to your figures in README.

Sorry for the confussion. The figures' titles are not correct, it should be \beta. I changed the notation a little bit.

**Comment by xujli** [comment]
> > > > > > > Could you tell me the bash commend you ran? And what's the accuracy of other methods?
> > > > > > 
> > > > > > 
> > > > > > I ran your methods of FedAvg, FedProx, Moon and FedMix in ./scripts/train_fmnist.sh with your presetting parameters. Final test accuracy of these methods when beta=0.1 are 85.77, 85.47, 78.86 and 74.55
> > > > > 
> > > > > 
> > > > > you also need to fine-tune for these methods
> > > > 
> > > > 
> > > > Yep I found this phenomenon in different beta settings, with more skewed data distribution, more performance gap between FedAvg and FedMix or Moon, from 10% to 1.3%. I still wonder the how your produce the results in Figure 4(a), is \alpha in your fig is \beta in your caption? I have not seen any result case that FedMix has better test accuracy than FedAvg. Thanks for your quick reply.
> > > 
> > > 
> > > \alpha is generation number of FedDPMS, \beta is Dirichlet Parameter
> > 
> > 
> > But in your figure, \alpha is concentration parameters, referring to your figures in README.
> 
> Sorry for the confussion. The figures' titles are not correct, it should be \beta. I changed the notation a little bit.

So with \beta=0.1 setting, how could FedMix be better than FedAvg.

**Comment by CityChan** [comment]
> > > > > > > > Could you tell me the bash commend you ran? And what's the accuracy of other methods?
> > > > > > > 
> > > > > > > 
> > > > > > > I ran your methods of FedAvg, FedProx, Moon and FedMix in ./scripts/train_fmnist.sh with your presetting parameters. Final test accuracy of these methods when beta=0.1 are 85.77, 85.47, 78.86 and 74.55
> > > > > > 
> > > > > > 
> > > > > > you also need to fine-tune for these methods
> > > > > 
> > > > > 
> > > > > Yep I found this phenomenon in different beta settings, with more skewed data distribution, more performance gap between FedAvg and FedMix or Moon, from 10% to 1.3%. I still wonder the how your produce the results in Figure 4(a), is \alpha in your fig is \beta in your caption? I have not seen any result case that FedMix has better test accuracy than FedAvg. Thanks for your quick reply.
> > > > 
> > > > 
> > > > \alpha is generation number of FedDPMS, \beta is Dirichlet Parameter
> > > 
> > > 
> > > But in your figure, \alpha is concentration parameters, referring to your figures in README.
> > 
> > 
> > Sorry for the confussion. The figures' titles are not correct, it should be \beta. I changed the notation a little bit.
> 
> So with \beta=0.1 setting, how could FedMix be better than FedAvg.

Could you provide the training log for FedMix? I got a result that FedMix is better than FedAvg with Fmnist with  \beta=0.1

**Comment by xujli** [comment]
I download your code and run your code with following bash command, only the device configuration is modified, I ran the code with single GPU.

    python3 train.py --dataset 'FMNIST' --batch_size 64 --lr 0.001 --num_epochs 50 --dropout_rate 0 --tag 'federated' --num_users 10 --update_frac 1 --local_ep 5 --beta 0.1 --seed 2 --mini 1 --pretrain 20 --gen_num 200 --std 4 --code_len 32 --alg 'FedAvg'

    python3 train.py --dataset 'FMNIST' --batch_size 64 --lr 0.001 --num_epochs 50 --dropout_rate 0 --tag 'federated' --num_users 10 --update_frac 1 --local_ep 5 --beta 0.1 --seed 2 --mini 1 --pretrain 20 --gen_num 200 --std 4 --code_len 32 --alg 'FedMix'

The logs on terminals:
FedAvg:
    Running CIFAR100 Training EXP
    # model parameters: 129005
Namespace(alg='FedAvg', batch_size=64, beta=0.1, classes=10, code_len=32, dataset='FMNIST', dropout_rate=0.0, eval_only=False, fedmix_lam=0.05, gen_num=200, inputchannel=1, inputsize=28, local_ep=5, log_frq=5, lr=0.001, lr_sh_rate=10, mini=1.0, moon_mu=5, moon_temp=0.5, num_epochs=50, num_users=10, pretrain=20, prox_mu=0.001, seed=2, std=4, tag='federated', update_frac=1.0, vae_mu=0.05)
  0%|                                                                                                                                                                         | 0/50 [00:00<?, ?it/s]
 | Global Training Round : 1 |

/home/huawei/anaconda3/envs/gle/lib/python3.8/site-packages/torch/nn/_reduction.py:42: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  warnings.warn(warning.format(ret))
accuracy of test at this round: 0.47143710191082805
  2%|███▏                                                                                                                                                          | 1/50 [02:17<1:52:14, 137.44s/it]
 | Global Training Round : 2 |

accuracy of test at this round: 0.6156449044585988
  4%|██████▎                                                                                                                                                       | 2/50 [04:39<1:51:57, 139.95s/it]
 | Global Training Round : 3 |

accuracy of test at this round: 0.7544785031847133
  6%|█████████▍                                                                                                                                                    | 3/50 [07:00<1:50:16, 140.78s/it]
 | Global Training Round : 4 |

accuracy of test at this round: 0.7336783439490446
  8%|████████████▋                                                                                                                                                 | 4/50 [09:22<1:48:16, 141.23s/it]
 | Global Training Round : 5 |

accuracy of test at this round: 0.7520899681528662
 10%|███████████████▊                                                                                                                                              | 5/50 [11:42<1:45:36, 140.81s/it]
 | Global Training Round : 6 |

accuracy of test at this round: 0.7749800955414012
 12%|██████████████████▉                                                                                                                                           | 6/50 [14:03<1:43:18, 140.88s/it]
 | Global Training Round : 7 |

accuracy of test at this round: 0.8248407643312102
 14%|██████████████████████                                                                                                                                        | 7/50 [16:25<1:41:04, 141.03s/it]
 | Global Training Round : 8 |

accuracy of test at this round: 0.8342953821656051
 16%|█████████████████████████▎                                                                                                                                    | 8/50 [18:47<1:39:03, 141.51s/it]
 | Global Training Round : 9 |

accuracy of test at this round: 0.8352906050955414
 18%|████████████████████████████▍                                                                                                                                 | 9/50 [21:10<1:36:56, 141.87s/it]
 | Global Training Round : 10 |

accuracy of test at this round: 0.8276273885350318
 20%|███████████████████████████████▍                                                                                                                             | 10/50 [23:32<1:34:35, 141.89s/it]
 | Global Training Round : 11 |

accuracy of test at this round: 0.8355891719745223
 22%|██████████████████████████████████▌                                                                                                                          | 11/50 [25:54<1:32:16, 141.96s/it]
 | Global Training Round : 12 |

accuracy of test at this round: 0.8310111464968153
 24%|█████████████████████████████████████▋                                                                                                                       | 12/50 [28:16<1:29:54, 141.95s/it]
 | Global Training Round : 13 |

accuracy of test at this round: 0.846437101910828
 26%|████████████████████████████████████████▊                                                                                                                    | 13/50 [30:38<1:27:34, 142.01s/it]
 | Global Training Round : 14 |

accuracy of test at this round: 0.8522093949044586
 28%|███████████████████████████████████████████▉                                                                                                                 | 14/50 [33:00<1:25:14, 142.07s/it]
 | Global Training Round : 15 |

accuracy of test at this round: 0.854796974522293
 30%|███████████████████████████████████████████████                                                                                                              | 15/50 [35:22<1:22:53, 142.10s/it]
 | Global Training Round : 16 |

accuracy of test at this round: 0.8313097133757962
 32%|██████████████████████████████████████████████████▏                                                                                                          | 16/50 [37:45<1:20:37, 142.29s/it]
 | Global Training Round : 17 |

accuracy of test at this round: 0.8495222929936306
 34%|█████████████████████████████████████████████████████▍                                                                                                       | 17/50 [40:07<1:18:12, 142.21s/it]
 | Global Training Round : 18 |

accuracy of test at this round: 0.8509156050955414
 36%|████████████████████████████████████████████████████████▌                                                                                                    | 18/50 [42:29<1:15:51, 142.22s/it]
 | Global Training Round : 19 |

accuracy of test at this round: 0.8549960191082803
 38%|███████████████████████████████████████████████████████████▋                                                                                                 | 19/50 [44:53<1:13:39, 142.56s/it]
 | Global Training Round : 20 |

accuracy of test at this round: 0.8471337579617835
 40%|██████████████████████████████████████████████████████████████▊                                                                                              | 20/50 [47:14<1:11:05, 142.18s/it]
 | Global Training Round : 21 |

accuracy of test at this round: 0.835390127388535
 42%|█████████████████████████████████████████████████████████████████▉                                                                                           | 21/50 [49:37<1:08:45, 142.27s/it]
 | Global Training Round : 22 |

accuracy of test at this round: 0.8513136942675159
 44%|█████████████████████████████████████████████████████████████████████                                                                                        | 22/50 [52:00<1:06:36, 142.74s/it]
 | Global Training Round : 23 |

accuracy of test at this round: 0.8528065286624203
 46%|████████████████████████████████████████████████████████████████████████▏                                                                                    | 23/50 [54:22<1:04:08, 142.53s/it]
 | Global Training Round : 24 |

accuracy of test at this round: 0.853702229299363
 48%|███████████████████████████████████████████████████████████████████████████▎                                                                                 | 24/50 [56:44<1:01:40, 142.33s/it]
 | Global Training Round : 25 |

accuracy of test at this round: 0.8522093949044586
 50%|███████████████████████████████████████████████████████████████████████████████▌                                                                               | 25/50 [59:06<59:16, 142.24s/it]
 | Global Training Round : 26 |

accuracy of test at this round: 0.8499203821656051
 52%|█████████████████████████████████████████████████████████████████████████████████▋                                                                           | 26/50 [1:01:30<57:00, 142.52s/it]
 | Global Training Round : 27 |

accuracy of test at this round: 0.852906050955414
 54%|████████████████████████████████████████████████████████████████████████████████████▊                                                                        | 27/50 [1:03:51<54:31, 142.23s/it]
 | Global Training Round : 28 |

accuracy of test at this round: 0.8622611464968153
 56%|███████████████████████████████████████████████████████████████████████████████████████▉                                                                     | 28/50 [1:06:13<52:08, 142.19s/it]
 | Global Training Round : 29 |

accuracy of test at this round: 0.8432523885350318
 58%|███████████████████████████████████████████████████████████████████████████████████████████                                                                  | 29/50 [1:08:35<49:44, 142.11s/it]
 | Global Training Round : 30 |

accuracy of test at this round: 0.8569864649681529
 60%|██████████████████████████████████████████████████████████████████████████████████████████████▏                                                              | 30/50 [1:10:58<47:25, 142.26s/it]
 | Global Training Round : 31 |

accuracy of test at this round: 0.8511146496815286
 62%|█████████████████████████████████████████████████████████████████████████████████████████████████▎                                                           | 31/50 [1:13:20<45:01, 142.18s/it]
 | Global Training Round : 32 |

accuracy of test at this round: 0.8499203821656051
 64%|████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                        | 32/50 [1:15:41<42:34, 141.90s/it]
 | Global Training Round : 33 |

accuracy of test at this round: 0.8470342356687898
 66%|███████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                     | 33/50 [1:18:02<40:10, 141.79s/it]
 | Global Training Round : 34 |

accuracy of test at this round: 0.8552945859872612
 68%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                  | 34/50 [1:20:22<37:36, 141.03s/it]
 | Global Training Round : 35 |

accuracy of test at this round: 0.8567874203821656
 70%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                               | 35/50 [1:22:44<35:20, 141.36s/it]
 | Global Training Round : 36 |

accuracy of test at this round: 0.84484474522293
 72%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                            | 36/50 [1:25:05<32:57, 141.28s/it]
 | Global Training Round : 37 |

accuracy of test at this round: 0.8520103503184714
 74%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                        | 37/50 [1:27:27<30:38, 141.42s/it]
 | Global Training Round : 38 |

accuracy of test at this round: 0.8443471337579618
 76%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                     | 38/50 [1:29:35<27:30, 137.55s/it]
 | Global Training Round : 39 |

accuracy of test at this round: 0.846437101910828
 78%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                  | 39/50 [1:31:40<24:32, 133.85s/it]
 | Global Training Round : 40 |

accuracy of test at this round: 0.8542993630573248
 80%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                               | 40/50 [1:33:41<21:39, 129.93s/it]
 | Global Training Round : 41 |

accuracy of test at this round: 0.8495222929936306
 82%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                            | 41/50 [1:35:45<19:13, 128.14s/it]
 | Global Training Round : 42 |

accuracy of test at this round: 0.8485270700636943
 84%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                         | 42/50 [1:37:52<17:02, 127.75s/it]
 | Global Training Round : 43 |

accuracy of test at this round: 0.8568869426751592
 86%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                      | 43/50 [1:39:59<14:51, 127.41s/it]
 | Global Training Round : 44 |

accuracy of test at this round: 0.855593152866242
 88%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                  | 44/50 [1:42:06<12:43, 127.25s/it]
 | Global Training Round : 45 |

accuracy of test at this round: 0.852906050955414
 90%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎               | 45/50 [1:44:05<10:25, 125.01s/it]
 | Global Training Round : 46 |

accuracy of test at this round: 0.851015127388535
 92%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍            | 46/50 [1:46:07<08:15, 123.96s/it]
 | Global Training Round : 47 |

accuracy of test at this round: 0.8549960191082803
 94%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌         | 47/50 [1:48:09<06:10, 123.51s/it]
 | Global Training Round : 48 |

accuracy of test at this round: 0.8507165605095541
 96%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋      | 48/50 [1:50:11<04:05, 122.87s/it]
 | Global Training Round : 49 |

accuracy of test at this round: 0.8505175159235668
 98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊   | 49/50 [1:52:12<02:02, 122.53s/it]
 | Global Training Round : 50 |

accuracy of test at this round: 0.8518113057324841
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [1:54:13<00:00, 137.08s/it]
max accuracy: 0.8622611464968153
running time:  6853.843099117279
   
   
   
FedMix:
Running CIFAR100 Training EXP
model parameters: 129005
Namespace(alg='FedMix', batch_size=64, beta=0.1, classes=10, code_len=32, dataset='FMNIST', dropout_rate=0.0, eval_only=False, fedmix_lam=0.05, gen_num=200, inputchannel=1, inputsize=28, local_ep=5, log_frq=5, lr=0.001, lr_sh_rate=10, mini=1.0, moon_mu=5, moon_temp=0.5, num_epochs=50, num_users=10, pretrain=20, prox_mu=0.001, seed=2, std=4, tag='federated', update_frac=1.0, vae_mu=0.05)
  0%|                                                                                                                                                                         | 0/50 [00:00<?, ?it/s]
 | Global Training Round : 1 |

/home/huawei/anaconda3/envs/gle/lib/python3.8/site-packages/torch/nn/_reduction.py:42: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  warnings.warn(warning.format(ret))
accuracy of test at this round: 0.39988057324840764
  2%|███▏                                                                                                                                                          | 1/50 [04:36<3:45:28, 276.10s/it]
 | Global Training Round : 2 |

accuracy of test at this round: 0.6518710191082803
  4%|██████▎                                                                                                                                                       | 2/50 [09:14<3:41:58, 277.47s/it]
 | Global Training Round : 3 |

accuracy of test at this round: 0.5499601910828026
  6%|█████████▍                                                                                                                                                    | 3/50 [13:31<3:30:04, 268.18s/it]
 | Global Training Round : 4 |

accuracy of test at this round: 0.7391520700636943
  8%|████████████▋                                                                                                                                                 | 4/50 [17:08<3:10:00, 247.83s/it]
 | Global Training Round : 5 |

accuracy of test at this round: 0.6746616242038217
 10%|███████████████▊                                                                                                                                              | 5/50 [20:43<2:57:02, 236.05s/it]
 | Global Training Round : 6 |

accuracy of test at this round: 0.7151671974522293
 12%|██████████████████▉                                                                                                                                           | 6/50 [24:16<2:47:22, 228.24s/it]
 | Global Training Round : 7 |

accuracy of test at this round: 0.7132762738853503
 14%|██████████████████████                                                                                                                                        | 7/50 [27:45<2:39:09, 222.09s/it]
 | Global Training Round : 8 |

accuracy of test at this round: 0.7284036624203821
 16%|█████████████████████████▎                                                                                                                                    | 8/50 [31:17<2:33:13, 218.89s/it]
 | Global Training Round : 9 |

accuracy of test at this round: 0.7289012738853503
 18%|████████████████████████████▍                                                                                                                                 | 9/50 [34:49<2:28:04, 216.68s/it]
 | Global Training Round : 10 |

accuracy of test at this round: 0.7402468152866242
 20%|███████████████████████████████▍                                                                                                                             | 10/50 [38:22<2:23:40, 215.50s/it]
 | Global Training Round : 11 |

accuracy of test at this round: 0.7372611464968153
 22%|██████████████████████████████████▌                                                                                                                          | 11/50 [41:57<2:20:00, 215.41s/it]
 | Global Training Round : 12 |

accuracy of test at this round: 0.7399482484076433
 24%|█████████████████████████████████████▋                                                                                                                       | 12/50 [45:35<2:16:47, 215.98s/it]
 | Global Training Round : 13 |

accuracy of test at this round: 0.742734872611465
 26%|████████████████████████████████████████▊                                                                                                                    | 13/50 [49:14<2:13:46, 216.92s/it]
 | Global Training Round : 14 |

accuracy of test at this round: 0.7423367834394905
 28%|███████████████████████████████████████████▉                                                                                                                 | 14/50 [52:48<2:09:44, 216.24s/it]
 | Global Training Round : 15 |

accuracy of test at this round: 0.7468152866242038
 30%|███████████████████████████████████████████████                                                                                                              | 15/50 [56:23<2:05:49, 215.70s/it]
 | Global Training Round : 16 |

accuracy of test at this round: 0.7488057324840764
 32%|██████████████████████████████████████████████████▏                                                                                                          | 16/50 [59:56<2:01:47, 214.91s/it]
 | Global Training Round : 17 |

accuracy of test at this round: 0.7555732484076433
 34%|████████████████████████████████████████████████████▋                                                                                                      | 17/50 [1:03:28<1:57:45, 214.09s/it]
 | Global Training Round : 18 |

accuracy of test at this round: 0.7541799363057324
 36%|███████████████████████████████████████████████████████▊                                                                                                   | 18/50 [1:07:00<1:53:49, 213.43s/it]
 | Global Training Round : 19 |

accuracy of test at this round: 0.7485071656050956
 38%|██████████████████████████████████████████████████████████▉                                                                                                | 19/50 [1:10:45<1:52:03, 216.88s/it]
 | Global Training Round : 20 |

accuracy of test at this round: 0.7504976114649682
 40%|██████████████████████████████████████████████████████████████                                                                                             | 20/50 [1:14:16<1:47:33, 215.12s/it]
 | Global Training Round : 21 |

accuracy of test at this round: 0.7594546178343949
 42%|█████████████████████████████████████████████████████████████████                                                                                          | 21/50 [1:17:43<1:42:47, 212.66s/it]
 | Global Training Round : 22 |

accuracy of test at this round: 0.7635350318471338
 44%|████████████████████████████████████████████████████████████████████▏                                                                                      | 22/50 [1:21:06<1:37:55, 209.86s/it]
 | Global Training Round : 23 |

accuracy of test at this round: 0.7588574840764332
 46%|███████████████████████████████████████████████████████████████████████▎                                                                                   | 23/50 [1:24:42<1:35:12, 211.57s/it]
 | Global Training Round : 24 |

accuracy of test at this round: 0.7575636942675159
 48%|██████████████████████████████████████████████████████████████████████████▍                                                                                | 24/50 [1:28:26<1:33:16, 215.24s/it]
 | Global Training Round : 25 |

accuracy of test at this round: 0.7588574840764332
 50%|█████████████████████████████████████████████████████████████████████████████▌                                                                             | 25/50 [1:32:01<1:29:41, 215.24s/it]
 | Global Training Round : 26 |

accuracy of test at this round: 0.75109474522293
 52%|████████████████████████████████████████████████████████████████████████████████▌                                                                          | 26/50 [1:35:40<1:26:37, 216.56s/it]
 | Global Training Round : 27 |

accuracy of test at this round: 0.7603503184713376
 54%|███████████████████████████████████████████████████████████████████████████████████▋                                                                       | 27/50 [1:39:15<1:22:47, 215.98s/it]
 | Global Training Round : 28 |

accuracy of test at this round: 0.7654259554140127
 56%|██████████████████████████████████████████████████████████████████████████████████████▊                                                                    | 28/50 [1:42:49<1:18:54, 215.23s/it]
 | Global Training Round : 29 |

accuracy of test at this round: 0.7612460191082803
 58%|█████████████████████████████████████████████████████████████████████████████████████████▉                                                                 | 29/50 [1:46:21<1:15:05, 214.53s/it]
 | Global Training Round : 30 |

accuracy of test at this round: 0.7582603503184714
 60%|█████████████████████████████████████████████████████████████████████████████████████████████                                                              | 30/50 [1:49:55<1:11:22, 214.10s/it]
 | Global Training Round : 31 |

accuracy of test at this round: 0.7625398089171974
 62%|████████████████████████████████████████████████████████████████████████████████████████████████                                                           | 31/50 [1:53:27<1:07:38, 213.62s/it]
 | Global Training Round : 32 |

accuracy of test at this round: 0.7617436305732485
 64%|███████████████████████████████████████████████████████████████████████████████████████████████████▏                                                       | 32/50 [1:57:01<1:04:05, 213.63s/it]
 | Global Training Round : 33 |

accuracy of test at this round: 0.7663216560509554
 66%|██████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                    | 33/50 [2:00:34<1:00:29, 213.51s/it]
 | Global Training Round : 34 |

accuracy of test at this round: 0.7630374203821656
 68%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                  | 34/50 [2:04:08<56:59, 213.71s/it]
 | Global Training Round : 35 |

accuracy of test at this round: 0.7724920382165605
 70%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                               | 35/50 [2:07:44<53:33, 214.26s/it]
 | Global Training Round : 36 |

accuracy of test at this round: 0.7577627388535032
 72%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                            | 36/50 [2:11:17<49:57, 214.09s/it]
 | Global Training Round : 37 |

accuracy of test at this round: 0.7655254777070064
 74%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                        | 37/50 [2:14:50<46:18, 213.75s/it]
 | Global Training Round : 38 |

accuracy of test at this round: 0.7642316878980892
 76%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                     | 38/50 [2:18:24<42:45, 213.81s/it]
 | Global Training Round : 39 |

accuracy of test at this round: 0.7550756369426752
 78%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                  | 39/50 [2:21:58<39:11, 213.75s/it]
 | Global Training Round : 40 |

accuracy of test at this round: 0.7534832802547771
 80%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                               | 40/50 [2:25:32<35:37, 213.72s/it]
 | Global Training Round : 41 |

accuracy of test at this round: 0.7711982484076433
 82%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                            | 41/50 [2:29:05<32:02, 213.64s/it]
 | Global Training Round : 42 |

accuracy of test at this round: 0.7699044585987261
 84%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                         | 42/50 [2:32:39<28:30, 213.75s/it]
 | Global Training Round : 43 |

accuracy of test at this round: 0.7620421974522293
 86%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                      | 43/50 [2:36:12<24:55, 213.67s/it]
 | Global Training Round : 44 |

accuracy of test at this round: 0.7655254777070064
 88%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                  | 44/50 [2:39:47<21:23, 213.88s/it]
 | Global Training Round : 45 |

accuracy of test at this round: 0.7605493630573248
 90%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎               | 45/50 [2:43:20<17:48, 213.79s/it]
 | Global Training Round : 46 |

accuracy of test at this round: 0.7609474522292994
 92%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍            | 46/50 [2:46:53<14:14, 213.51s/it]
 | Global Training Round : 47 |

accuracy of test at this round: 0.7640326433121019
 94%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌         | 47/50 [2:50:26<10:39, 213.18s/it]
 | Global Training Round : 48 |

accuracy of test at this round: 0.7669187898089171
 96%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋      | 48/50 [2:53:58<07:05, 212.83s/it]
 | Global Training Round : 49 |

accuracy of test at this round: 0.7617436305732485
 98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊   | 49/50 [2:57:31<03:33, 213.11s/it]
 | Global Training Round : 50 |

accuracy of test at this round: 0.7641321656050956
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [3:01:04<00:00, 217.28s/it]
max accuracy: 0.7724920382165605
running time:  10864.158665895462

**Comment by xujli** [comment]
![image](https://user-images.githubusercontent.com/49027206/179654064-5ea91fab-098d-4a41-9a40-d591a6a2c936.png)
I use t-sne to visualize feature representation, it seems that Mix methods learn better representations, but it doesn't show on the final accuracy.
![image](https://user-images.githubusercontent.com/49027206/179654459-0ac56884-69b3-49e0-88bf-0b3fdffa4c9b.png)

**Comment by xujli** [comment]
I log test loss in your framework, FedAvg and FedMix are 0.861 and 0.965. The figures above is my implement in other project.

**Comment by CityChan** [comment]
> 

could you change the seed (random seed) and have multi runs? The results in the figure are averages of multi-run.
Please set seed from 0,1,2,3,4

**Comment by CityChan** [comment]
> 我在您的框架中记录测试损失，FedAvg 和 FedMix 分别为 0.861 和 0.965。上图是我在其他项目中的实现。

I think FedMix's performance is really depending on the data partition.

**Comment by xujli** [comment]
ok, i will try it.

**Comment by xujli** [comment]
Final accuracy and test loss in my implements
|seed|FedAvg|FedMix|
|---|---|---|
|0|0.8457404458598726 0.8297305997389897  |0.7837380573248408 0.8556345951784948|
|1|0.8525079617834395 0.7843629762435415  |0.7971735668789809 0.9739306443815778|
|2|0.8559912420382165 0.8610615460735977  |0.7335788216560509 0.9652924951474378|
|3|0.8514132165605095 0.8472948785230612  |0.7772691082802548 0.9367749569522348|
|4|0.8240445859872612 1.5730794315125531  |0.81140525477707 0.9078551811777102|
pytorch==1.10.

**Comment by CityChan** [comment]
> Final accuracy and test loss in my implements
> 
> seed	FedAvg	FedMix
> 0	0.8457404458598726 0.8297305997389897	0.7837380573248408 0.8556345951784948
> 1	0.8525079617834395 0.7843629762435415	0.7971735668789809 0.9739306443815778
> 2	0.8559912420382165 0.8610615460735977	0.7335788216560509 0.9652924951474378
> 3	0.8514132165605095 0.8472948785230612	0.7772691082802548 0.9367749569522348
> 4	0.8240445859872612 1.5730794315125531	0.81140525477707 0.9078551811777102
> pytorch==1.10.

Here is my jupyter notebook for training fedmix. FYI
https://drive.google.com/file/d/13PWn720l4j-xVmV6tM_IlEc6yyHRJBWM/view?usp=sharing

**Comment by xujli** [comment]
Thanks, I'll check the details.
